image: alpine:latest

definitions:
  steps:
    - step: &build-and-test
        name: Build and run tests
        caches:
          - gradle
          - node
        script:
          - apk add gradle npm
          - npm install -g ganache-cli
          - ganache-cli -m "candy maple cake sugar pudding cream honey rich smooth crumble sweet treat" --port 8544 --accounts 20 --networkId=9 --gasLimit=10000000 > /dev/null &
          - ./gradlew build
pipelines:
  default:
    - step: *build-and-test
  custom:
    docker-image-deploy:
      - variables:
        - name: version
      - step:
          <<: *build-and-test
          artifacts:
            - build/**
            - src/main/resources/**
      - step:
          name: Push to Docker Hub
          script:
            - docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
            - docker build -t openchargingnetwork/ocn-node:${version} -t openchargingnetwork/ocn-node:latest .
            - docker push openchargingnetwork/ocn-node:${version}
            - docker push openchargingnetwork/ocn-node:latest
          services:
            - docker
