/*
    Copyright 2019 Energy Web Foundation

    This file is part of Open Charging Network Client.

    Open Charging Network Client is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    Open Charging Network Client is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with Open Charging Network Client.  If not, see <https://www.gnu.org/licenses/>.
*/

package snc.openchargingnetwork.client.controllers.ocpi

import org.springframework.web.bind.annotation.GetMapping
import org.springframework.web.bind.annotation.RequestHeader
import org.springframework.web.bind.annotation.RequestMapping
import org.springframework.web.bind.annotation.RestController
import snc.openchargingnetwork.client.repositories.PlatformRepository
import snc.openchargingnetwork.client.config.Properties
import snc.openchargingnetwork.client.models.ocpi.InterfaceRole
import snc.openchargingnetwork.client.models.ocpi.ModuleID
import snc.openchargingnetwork.client.models.ocpi.OcpiStatus
import snc.openchargingnetwork.client.models.exceptions.OcpiClientInvalidParametersException
import snc.openchargingnetwork.client.models.ocpi.*
import snc.openchargingnetwork.client.tools.extractToken
import snc.openchargingnetwork.client.tools.urlJoin

@RestController
@RequestMapping("/ocpi")
class VersionsController(private val repository: PlatformRepository,
                         private val properties: Properties) {

    @GetMapping("/versions")
    fun getVersions(@RequestHeader("Authorization") authorization: String): OcpiResponse<Versions> {

        // check authorization TOKEN_A exists (generated by admin)
        return if (repository.existsByAuth_TokenA(authorization.extractToken())) {

            // prepare OCPI version information body
            val endpoint = urlJoin(properties.url, "/ocpi/2.2")
            val versions = Versions(versions = listOf(Version("2.2", endpoint)))
            OcpiResponse(
                    OcpiStatus.SUCCESS.code,
                    data = versions)

        } else {
            throw OcpiClientInvalidParametersException("Invalid CREDENTIALS_TOKEN_A")
        }
    }

    @GetMapping("/2.2")
    fun getVersionsDetail(@RequestHeader("Authorization") authorization: String): OcpiResponse<VersionDetail> {

        // check authorization TOKEN_A exists (generated by admin)
        return if (repository.existsByAuth_TokenA(authorization.extractToken())) {

            val endpoints = mutableListOf<Endpoint>()

            // prepare EMSP and SENDER interfaces for each module
            for (module in ModuleID.values()) {

                // these modules have only SENDER endpoint (the broker/hub)
                if (module.id == "credentials" || module.id == "hubclientinfo") {

                    endpoints.add(Endpoint(
                            identifier = module.id,
                            role = InterfaceRole.SENDER,
                            url = urlJoin(properties.url, "/ocpi/2.2/${module.id}")))

                // not yet implemented
                } else if (module.id == "chargingprofiles") {

                    continue

                // remaining modules all have both interfaces implemented
                } else {

                    endpoints.addAll(listOf(
                            Endpoint(
                                    identifier = module.id,
                                    role = InterfaceRole.SENDER,
                                    url = urlJoin(properties.url, "/ocpi/sender/2.2/${module.id}")),
                            Endpoint(
                                    identifier = module.id,
                                    role = InterfaceRole.RECEIVER,
                                    url = urlJoin(properties.url, "/ocpi/receiver/2.2/${module.id}"))))
                }

            }

            OcpiResponse(
                    OcpiStatus.SUCCESS.code,
                    data = VersionDetail("2.2", endpoints))

        } else {
            throw OcpiClientInvalidParametersException("Invalid CREDENTIALS_TOKEN_A")
        }
    }
}