package snc.openchargingnetwork.client.controllers.ocpi

import org.springframework.web.bind.annotation.GetMapping
import org.springframework.web.bind.annotation.RequestHeader
import org.springframework.web.bind.annotation.RequestMapping
import org.springframework.web.bind.annotation.RestController
import snc.openchargingnetwork.client.repositories.PlatformRepository
import snc.openchargingnetwork.client.config.Properties
import snc.openchargingnetwork.client.models.ocpi.InterfaceRole
import snc.openchargingnetwork.client.models.ocpi.ModuleID
import snc.openchargingnetwork.client.models.ocpi.OcpiStatus
import snc.openchargingnetwork.client.models.exceptions.OcpiClientInvalidParametersException
import snc.openchargingnetwork.client.models.ocpi.*
import snc.openchargingnetwork.client.tools.extractToken
import snc.openchargingnetwork.client.tools.urlJoin

@RestController
@RequestMapping("/ocpi")
class VersionsController(private val repository: PlatformRepository,
                         private val properties: Properties) {

    @GetMapping("/versions")
    fun getVersions(@RequestHeader("Authorization") authorization: String): OcpiResponse<Versions> {

        // check authorization TOKEN_A exists (generated by admin)
        return if (repository.existsByAuth_TokenA(authorization.extractToken())) {

            // prepare OCPI version information body
            val endpoint = urlJoin(properties.url, "/ocpi/2.2")
            val versions = Versions(versions = listOf(Version("2.2", endpoint)))
            OcpiResponse(
                    OcpiStatus.SUCCESS.code,
                    data = versions)

        } else {
            throw OcpiClientInvalidParametersException("Invalid CREDENTIALS_TOKEN_A")
        }
    }

    @GetMapping("/2.2")
    fun getVersionsDetail(@RequestHeader("Authorization") authorization: String): OcpiResponse<VersionDetail> {

        // check authorization TOKEN_A exists (generated by admin)
        return if (repository.existsByAuth_TokenA(authorization.extractToken())) {

            val endpoints = mutableListOf<Endpoint>()

            // prepare EMSP and SENDER interfaces for each module
            for (id in ModuleID.values()) {

                // these modules have only SENDER endpoint (the broker/hub)
                if (id.value == "credentials" || id.value == "hubclientinfo") {

                    endpoints.add(Endpoint(
                            identifier = id.value,
                            role = InterfaceRole.SENDER,
                            url = urlJoin(properties.url, "/ocpi/2.2/${id.value}")))

                // not yet implemented
                } else if (id.value == "chargingprofiles") {

                    continue

                // remaining modules all have both interfaces implemented
                } else {

                    endpoints.addAll(listOf(
                            Endpoint(
                                    identifier = id.value,
                                    role = InterfaceRole.SENDER,
                                    url = urlJoin(properties.url, "/ocpi/sender/2.2/${id.value}")),
                            Endpoint(
                                    identifier = id.value,
                                    role = InterfaceRole.RECEIVER,
                                    url = urlJoin(properties.url, "/ocpi/receiver/2.2/${id.value}"))))
                }

            }

            OcpiResponse(
                    OcpiStatus.SUCCESS.code,
                    data = VersionDetail("2.2", endpoints))

        } else {
            throw OcpiClientInvalidParametersException("Invalid CREDENTIALS_TOKEN_A")
        }
    }
}