name: Build and Test Node

on:
  pull_request:
    branches:
      - develop
      - master

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - name: Install ganache
        run: |
          sudo apt-get update && apt-get upgrade
          sudo apt-get install npm
          sudo npm i -g ganache-cli
          ganache-cli -m "candy maple cake sugar pudding cream honey rich smooth crumble sweet treat" --port 8544 --accounts 20 --networkId=9 --gasLimit=10000000 > /dev/null &

      - name: Setup JDK/Gradle
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '14'
          cache: 'gradle'

      - name: Build
        run: ./gradlew build --no-daemon
